"use client";

import { motion } from "framer-motion";
import Link from "next/link";

const ease = [0.32, 0.72, 0, 1] as const;

const sections = [
  {
    id: "01",
    title: "Acceptance of Terms",
    body: `By accessing or using Vertex ("the Platform"), you agree to be bound by these Terms of Use. If you do not agree, do not use the Platform.

These Terms apply to all users, including freelancers, clients, and any other party who interacts with invoices, contracts, or payment links generated via Vertex.`,
  },
  {
    id: "02",
    title: "Description of Service",
    body: `Vertex is a payment infrastructure platform built on the Solana blockchain that enables users to:

— Create and share crypto-denominated invoices and payment links
— Draft service agreement documents
— Track and record payment status on-chain

Vertex does not hold, custody, or transfer funds on your behalf. All blockchain transactions are executed directly between sender and recipient wallets.`,
  },
  {
    id: "03",
    title: "Eligibility",
    body: `You must be at least 18 years of age to use Vertex. By using the Platform, you represent and warrant that you have the legal capacity to enter into a binding agreement.

Vertex may be unavailable in certain jurisdictions where cryptocurrency payment services are restricted or prohibited. It is your responsibility to ensure compliance with local laws.`,
  },
  {
    id: "04",
    title: "Platform Fees",
    body: `Vertex charges a platform fee of 0.5% on each completed payment processed through the Platform. This fee is deducted automatically at the time of transaction.

No fee is charged for invoice creation, contract generation, payment link creation, or account management. There are no subscription or monthly fees.

Solana network fees (gas) are separate and paid by the sender's wallet at the time of the transaction. These fees are not collected by Vertex.`,
  },
  {
    id: "05",
    title: "Blockchain Transactions",
    body: `All payments on Vertex are settled on the Solana blockchain. Blockchain transactions are:

— Irreversible once confirmed on-chain
— Subject to network conditions outside Vertex's control
— Not guaranteed to succeed in the event of RPC outages or network congestion

You are solely responsible for verifying recipient wallet addresses before initiating any payment. Vertex cannot reverse, cancel, or recover funds from an incorrect or fraudulent address.`,
  },
  {
    id: "06",
    title: "Wallet Connectivity",
    body: `Vertex integrates with third-party Solana wallet adapters (e.g. Phantom, Backpack, Solflare). Vertex does not store your private keys, seed phrases, or wallet credentials.

Any loss of access to your wallet is outside Vertex's control and responsibility. You assume all risks associated with wallet management, private key storage, and wallet security.`,
  },
  {
    id: "07",
    title: "User Conduct",
    body: `You agree not to use Vertex to:

— Facilitate illegal transactions or money laundering
— Generate fraudulent invoices or payment requests
— Circumvent or interfere with blockchain transaction mechanisms
— Reverse-engineer, copy, or scrape the Platform
— Engage in any activity that disrupts the Platform or Solana network infrastructure`,
  },
  {
    id: "08",
    title: "Intellectual Property",
    body: `All content, code, brand assets, and documentation on the Vertex Platform are the intellectual property of Vertex and its creator. Unauthorised reproduction, distribution, or commercial use of Platform materials is prohibited.

Documents generated by users (invoices, contracts, payment links) belong to the respective users and clients involved. Vertex claims no ownership over user-generated content.`,
  },
  {
    id: "09",
    title: "Disclaimer of Warranties",
    body: `Vertex is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that:

— The Platform will be uninterrupted or error-free
— Blockchain transactions will confirm within any specific time frame
— The Platform will be free from security vulnerabilities

Your use of Vertex is at your sole risk.`,
  },
  {
    id: "10",
    title: "Limitation of Liability",
    body: `To the maximum extent permitted by law, Vertex and its creator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform, including but not limited to:

— Loss of crypto assets due to incorrect wallet addresses
— Failed or delayed blockchain transactions
— Unauthorised access to your wallet or account

Our total liability to you, in any circumstance, shall not exceed the fees paid by you to Vertex in the 30 days preceding the event giving rise to the claim.`,
  },
  {
    id: "11",
    title: "Termination",
    body: `Vertex reserves the right to suspend or terminate access to the Platform at any time, for any reason, including violation of these Terms.

You may stop using the Platform at any time. Termination does not affect on-chain records or transactions already processed.`,
  },
  {
    id: "12",
    title: "Changes to Terms",
    body: `We may update these Terms of Use from time to time. Continued use of the Platform after any update constitutes acceptance of the new Terms.

The "Last updated" date at the top of this page indicates when the Terms were last revised. We recommend reviewing this page periodically.`,
  },
  {
    id: "13",
    title: "Governing Law",
    body: `These Terms are governed by applicable law. Any disputes arising under these Terms shall be resolved through binding arbitration, unless you are located in a jurisdiction that prohibits mandatory arbitration.

For questions about these Terms, contact us at priiincema@gmail.com.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-[100dvh] relative overflow-x-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Hero */}
        <section className="pt-32 pb-16">
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease }}
            className="text-[10px] font-black uppercase tracking-[0.4em] text-primary mb-6"
          >
            Legal
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.1, ease }}
            className="text-5xl lg:text-7xl font-black tracking-tighter text-white leading-[0.9] mb-8"
          >
            TERMS
            <br />
            <span className="text-primary italic">OF USE.</span>
          </motion.h1>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.6 }}
            className="flex flex-wrap gap-6 text-xs text-white/30"
          >
            <span>Last updated: <span className="text-white/50 font-bold">May 2025</span></span>
            <span>Effective: <span className="text-white/50 font-bold">Immediately</span></span>
          </motion.div>
        </section>

        {/* Intro banner */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.35, duration: 0.6, ease }}
          className="mb-16 p-6 bg-primary/5 border border-primary/15 rounded-2xl"
        >
          <p className="text-sm text-white/60 leading-relaxed">
            Please read these Terms of Use carefully before using the Vertex
            platform. These Terms govern your access to and use of all Vertex
            services, including invoice creation, contract drafting, and
            on-chain payment processing.
          </p>
        </motion.div>

        {/* Sections */}
        <div className="space-y-1 pb-32">
          {sections.map((s, i) => (
            <motion.div
              key={s.id}
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.03, ease }}
              className="border-b border-white/5 py-10 group"
            >
              <div className="flex gap-8 items-start">
                <span className="text-[10px] font-black text-white/15 tracking-widest pt-1 min-w-[28px]">
                  {s.id}
                </span>
                <div className="flex-1">
                  <h2 className="text-lg font-black text-white tracking-tight mb-5">
                    {s.title}
                  </h2>
                  <div className="text-white/50 text-sm leading-relaxed whitespace-pre-line">
                    {s.body}
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Footer nav */}
        <div className="pb-24 flex flex-wrap gap-6 text-xs">
          <Link href="/privacy" className="text-white/30 hover:text-primary transition-colors cursor-pointer">
            Privacy Policy
          </Link>
          <Link href="/cookies" className="text-white/30 hover:text-primary transition-colors cursor-pointer">
            Cookie Policy
          </Link>
          <Link href="/contact" className="text-white/30 hover:text-primary transition-colors cursor-pointer">
            Contact Us
          </Link>
        </div>
      </div>
    </div>
  );
}
